### PR TITLE
Multiple indices of the same auxiliary are all matched

### LINKED ISSUE #793: Passive voice research does not look for new auxiliary after stopword
A customer sent us the following sentence that is marked as passive:

> He thought she was the only one who knew about the six other women buried beneath the rows of corn in his back yard, but he was wrong.

The auxiliary-verb combination that is found is 'was ... buried'. This should not be possible because of the stopword 'who'. After the stop word, it should look for a new auxiliary first, and then, and only then, look for an -ed-word or irregular. 

N.B. The stop word is correctly breaking the sentence into subsentences: the subsentences it returns are 'was the only one' and 'who knew about the six other women buried beneath the rows of corn in his back yard, but he was wrong'

### PR DESCRIPTION
**Pull request by terw-dan**
Fixes #793. 

The problem in 793 was that the index of the second occurence of 'was' was discarded, since we only saved the first index of an auxiliary. 
This makes sure all indices are saved for auxiliaries, so we don't report sentences being passive, when they are not. 
Because the sentence was not split on the second 'was', the subsentenced validated since there was a auxiliary in there, but only after a verb ending in -ed. 

For testing, use a sentence with the same auxiliary twice (like the example in 793).

### CODE REVIEW

File: js/researches/getPassiveVoice.js [hunk 1]
```diff
@@ -25,6 +25,23 @@ var ingExclusionArray = [ "king", "cling", "ring", "being" ];
 var irregularExclusionArray = [ "get", "gets", "getting", "got", "gotten" ];
 
 /**
+ * Returns the indices of a string in a sentence. If it is found multiple times, will return multiple indices.
```
Comment (jcomack) [inline js/researches/getPassiveVoice.js]: Missing `it` between `[...] multiple times, _it_ will [...]`.

File: js/researches/getPassiveVoice.js [hunk 2]
```diff
@@ -25,6 +25,23 @@ var ingExclusionArray = [ "king", "cling", "ring", "being" ];
...
+ *
+ * @param {string} part The part to find in the sentence.
+ * @param {string} sentence The sentence to check for parts.
+ * @returns {Array} All indices found.
+ */
+function getIndicesOf( part, sentence ) {
+	var startIndex = 0, searchStrLen = part.length;
```
Comment (jcomack) [inline js/researches/getPassiveVoice.js]: Don't abbreviate variables.

Comment (jcomack) [inline js/researches/getPassiveVoice.js]: Registering multiple variables on a single line doesn't do the readability of the  code any good.

File: js/researches/getPassiveVoice.js [hunk 3]
```diff
@@ -37,12 +54,14 @@ var matchArray = function( sentence, matches ) {
 
 	forEach( matches, function( part ) {
 		part = stripSpaces( part );
+		var indices = getIndicesOf( part, sentence );
```
Comment (jcomack) [inline js/researches/getPassiveVoice.js]: This line is being executed early on, although it's possible that there are no matches. I'd place this line _after_ `if ( !matchWordInSentence( part, sentence ) ) { ... }`.

File: js/researches/getPassiveVoice.js [hunk 4]
```diff
@@ -37,12 +54,14 @@ var matchArray = function( sentence, matches ) {
...
 
 		if ( !matchWordInSentence( part, sentence ) ) {
 			return;
 		}
-
-		matchedParts.push( { index: sentence.indexOf( part ), match: part } );
+		forEach( indices, function( index ) {
+			matchedParts.push( { index: index, match: part } );
```
Comment (jcomack) [inline js/researches/getPassiveVoice.js]: Aren't you more or less doing the same thing here as you did in `getIndicesOf()`? Wouldn't it make more sense to do all these actions in a single loop?

File: spec/researches/passiveVoiceSpec.js [hunk 5]
```diff
@@ -353,5 +353,12 @@ describe( "detecting passive voice in sentences", function() {
 			total: 1,
 			passives: []
 		} );
-	})
+	});
+
+	it( "returns no passive sentence when the subsentence has no auxiliary, when the auxiliary is used multiple times", function () {
+		// Passive: no passive, auxiliary: was
+		paper = new Paper("He thought she was the one who knew about the six buried in his back yard, but he was wrong.");
```
Comment (jcomack) [inline spec/researches/passiveVoiceSpec.js]: Missing spaces after `(` and before `)`.

**Comment by jcomack** [comment]
CR done 🚧

**Comment by jcomack** [comment]
CR 2 done :

**Comment by boblinthorst** [comment]
Acceptance: ok 👍
