### PR TITLE
Fix sentence beginning assessment. 

### LINKED ISSUE #619: Incorrect marking of repeated sentence beginnings
### What did you expect to happen?
The marker to mark all sentences starting with the same word (in case of 3 consecutive sentences or more).

### What happened instead?
The marker only marked the first and second sentence with repeated sentence beginnings:
schermafbeelding 2016-06-07 om 13 22 30

### How can we reproduce this behavior?
Start 3 consecutive sentences with the same word (not the/a/those/that/that/these/one/.../ten), with a `<p>` and `</p>` between the second and third sentence. 

### Technical info
* Platform: WordPress 
* Platform version: 4.5.2
* Yoast SEO version: trunk

### LINKED ISSUE #727: Fix sentencebeginnings assessment.
reintroduce the sentence beginnings.

### PR DESCRIPTION
**Pull request by terw-dan**
Fixes #727
Fixes #619 

This PR reintroduces the sentence begining assessment and adds enhancements for detection. 
Added tests for matching first sentences with different capitalization and with different tags. 

Now converts all words to lowercase, this makes sure we can match the exception words, regardless of their casing. The converted words are only used for this check, so the markings work like expected. 

For testing:
Test the assessment in the standalone example, and test with different tags to make sure these work.

### CODE REVIEW

File: js/researches/getSentenceBeginnings.js [hunk 1]
```diff
@@ -4,14 +4,17 @@ var stripSpaces = require( "../stringProcessing/stripSpaces.js" );
 var removeNonWordCharacters = require( "../stringProcessing/removeNonWordCharacters.js" );
 var firstWordExceptions = require ( "../language/en/firstWordExceptions.js" )();
 
+var isEmpty = require( "lodash/isEmpty" );
+var forEach = require( "lodash/forEach" );
 /**
```
Comment (jcomack) [inline js/researches/getSentenceBeginnings.js]: Could you please add a newline.

File: js/researches/getSentenceBeginnings.js [hunk 2]
```diff
@@ -4,14 +4,17 @@ var stripSpaces = require( "../stringProcessing/stripSpaces.js" );
...
- * @param {array} sentenceBeginnings The array containing the first word of each sentence.
- * @param {number} i The iterator for the sentenceBeginning array.
+ *
+ * @param {string} currentSentenceBeginning The first word of the current sentence.
+ * @param {string} nextSentenceBeginning The first word of the next sentence.
  * @returns {boolean} Returns true if sentence beginnings match.
  */
-var matchSentenceBeginnings = function( sentenceBeginnings, i ) {
-	if ( sentenceBeginnings[ i ] === sentenceBeginnings[ i + 1 ] ) {
+var hasSameBeginWord = function( currentSentenceBeginning, nextSentenceBeginning ) {
```
Comment (jcomack) [inline js/researches/getSentenceBeginnings.js]: I'd rename this to `hasSameStartingWord` or `startsWithSameWord`.

File: js/researches/getSentenceBeginnings.js [hunk 3]
```diff
@@ -4,14 +4,17 @@ var stripSpaces = require( "../stringProcessing/stripSpaces.js" );
...
+	if( !isEmpty( currentSentenceBeginning ) && currentSentenceBeginning === nextSentenceBeginning ) {
```
Comment (jcomack) [inline js/researches/getSentenceBeginnings.js]: Missing space after `if`.

File: js/researches/getSentenceBeginnings.js [hunk 4]
```diff
@@ -24,21 +27,24 @@ var matchSentenceBeginnings = function( sentenceBeginnings, i ) {
...
-			foundSentences.push( sentences[ i ] );
-			count++;
+	var sameBeginnings = 1;
+
+	forEach( sentenceBeginnings, function( beginning, i ) {
+		var currentSentenceBeginning = beginning;
+		var nextSentenceBeginning = sentenceBeginnings[ i + 1 ];
+		foundSentences.push( sentences );
+
+		if( hasSameBeginWord( currentSentenceBeginning, nextSentenceBeginning ) ) {
```
Comment (jcomack) [inline js/researches/getSentenceBeginnings.js]: Missing space after `if`.

**Comment by jcomack** [comment]
CR done 🚧

**Comment by jcomack** [comment]
CR 2 done 👍

**Comment by rensw90** [comment]
Acceptance done, tekst didn't mark.

**Comment by rensw90** [comment]
CR 3 done 👍

**Comment by rensw90** [comment]
Acceptance done 👍
