### PR TITLE
Catch exception thrown by assessments

### LINKED ISSUE #456: Gracefully fail on assessment failure
If an assessment throws an error such as happened in #... we should gracefully fail and not show that assessment or show an error instead of breaking the complete JavaScript.

This makes our code much more robust.

### PR DESCRIPTION
**Pull request by atimmer**
How to test this: Introduce an error in an assessment and make sure the
assessment is now a gray cirlce with an error message the trace is in
the console and the rest of the content analysis still works.

Fixes #456

### CODE REVIEW

File: js/assessor.js [hunk 1]
```diff
@@ -125,19 +126,45 @@ Assessor.prototype.assess = function( paper ) {
...
 			result.setMarker( this.getMarker( assessment, paper, researcher ) );
 		}
+	} catch ( assessmentError ) {
+		showTrace( assessmentError );
+
+		result = new AssessmentResult();
+
+		result.setScore( 0 );
+		result.setText( this.i18n.sprintf(
+			this.i18n.dgettext( "js-text-analysis", "An error occured in the '%1$s' assessment, " +
```
Comment (moorscode) [inline js/assessor.js]: Do we want to confuse people with "the console"?
I guess just putting it in the console and leaving it there for support to ask for it would be a bit more user friendly.

File: js/helpers/errors.js [hunk 2]
```diff
@@ -0,0 +1,23 @@
+var isUndefined = require( "lodash/isUndefined" );
+
+/**
+ * Shows and error trace of the error message in the console if the console is available.
+ *
+ * @param {string} [errorMessage=""] The error message.
+ */
+function showTrace( errorMessage ) {
+	if ( isUndefined( errorMessage ) ) {
+		errorMessage = "";
```
Comment (moorscode) [inline js/helpers/errors.js]: Why not just exit when there is no message?

**Comment by moorscode** [comment]
CR Done :construction_worker:

File: js/helpers/errors.js (hunk 2 above)
Comment (atimmer) [inline js/helpers/errors.js]: Because I want to be able to call this function without an error message and still put a trace in the console.

**Comment by moorscode** [comment]
CR Done 👍

**Comment by terw-dan** [comment]
Acceptance :+1:
