### PR TITLE
Check keyword in meta description only when there is a meta description

### LINKED ISSUE #1478: Meta description keyword assessment gives incorrect feedback
When a keyword but no meta description has been specified, the meta description keyword assessment gives the following feedback string: `A meta description has been specified, but it does not contain the focus keyword.`

This feedback should only be triggered once a meta description has been set.

### PR DESCRIPTION
**Pull request by manuelaugustin**
## Summary

This PR can be summarized in the following changelog entry:

n/a

## Relevant technical choices:

* Changes the assessment so that it checks whether there's a keyword in the meta description only when a meta description has been set.

## Test instructions

This PR can be tested by following these steps:

### Browserified
* Check out this branch.
* Use the browserified example. Don't forget to run a `grunt build:js`.
* Add a keyword and add a meta description that does not contain the keyword. There should be no feedback that says that you haven't used the keyword in the meta description. This feedback should only appear once you add text to the meta description.

### WordPress
* Use the beta script to combine this branch with `stories/9718-change-meta-description-keyword-taxonomy-assessor-specs `on `wordpress-seo` (or, if that has already been merged, use `feature/recalibration`). 
* Test the same functionality as specified above. Check also whether this works for category pages.

Fixes #1478

### CODE REVIEW

File: src/assessments/seo/metaDescriptionKeywordAssessment.js [hunk 1]
```diff
@@ -41,7 +41,7 @@ class MetaDescriptionKeywordAssessment extends Assessment {
 	 */
 	getResult( paper, researcher, i18n ) {
 		this._keywordMatches = researcher.getResearch( "metaDescriptionKeyword" );
-		var assessmentResult = new AssessmentResult();
+		let assessmentResult = new AssessmentResult();
 
 		assessmentResult.setScore( this.calculateScore() );
 		assessmentResult.setText( this.translateScore( i18n ) );
```
Comment (nataliashitova) [inline src/assessments/seo/metaDescriptionKeywordAssessment.js]: For the sake of consistency with the other SEO assessments and also for convenience of editing, please define the feedback strings in the configuration instead of in the function `translateScore`.

**Comment by manuelaugustin** [comment]
Moved to blocked until we can confirm whether the current class refactoring works with Jed/translator comments

**Comment by nataliashitova** [comment]
CR and acceptance done 👍
