### PR TITLE
Fixes flesch reading ease score

### LINKED ISSUE #542: cleanText.js forces text.toLocaleLowerCase invalidating countSentences() on
Apologies if I'm not giving the correct info, this is my first issue.

Working from example code, cleanText.js forces text to text.toLocaleLowerCase(). When this is parsed by filterPositions (in getSentences.js) it triggers invalidateOnCapital(), and always returns a sentence count of one, generating a Flesch Score of 0

image

### Technical info
* Platform: Standalone
* Yoast SEO version: 1.2.2

### LINKED ISSUE #544: Flesch reading ease is broken
### What did you expect to happen?
Flesch reading ease to give a proper result for my text.

### What happened instead?
It returned 0.

### How can we reproduce this behavior?
Feed it basically any test.

### Technical info
* Platform: WordPress
* Platform version: Trunk
* Yoast SEO version: Trunk

### PR DESCRIPTION
**Pull request by atimmer**
How to test this: The flesch reading ease score should now always be
correct. Especially when testing in combination with the improved
sentence detection.

Fixes #544 
Fixes #542

### CODE REVIEW

File: spec/researches/fleschReadingSpec.js [hunk 1]
```diff
@@ -6,11 +6,11 @@ describe("a test to calculate the fleschReading score", function(){
 
 		var mockPaper = new Paper( "A piece of text to calculate scores." );
 		expect( fleschFunction( mockPaper ) ).toBe( 78.9 );
-/*
+
 // todo This spec is currently disabled, because the fleschreading still runs a cleantext, that removes capitals. This is fixed in #496 of YoastSEO
```
Comment (terw-dan) [inline spec/researches/fleschReadingSpec.js]: This comment can be removed if it is working now.

**Comment by terw-dan** [comment]
CR Done

**Comment by terw-dan** [comment]
Acceptance :+1:
