### PR TITLE
Fixes passive sentence breakers matching

### LINKED ISSUE #1214: Passive sentence breakers not correctly identified
## What did you expect to happen?
Passive sentence breakers should be identified also when there’s a preceding word containing the same string of letters.

## What happened instead?
For example, the sentence fragment `who commented praise is due` is not passive, but according to the analysis, it is. When 'praise' is removed from the sentence, the analysis is correct.

### PR DESCRIPTION
**Pull request by manuelaugustin**
## Summary

This PR can be summarized in the following changelog entry: Fixes the bug where the passive voice and transition word assessments were broken when the passive voice sentence breaker or the transition word was preceded by a word containing the same string of letters. For example, 'is' was not recognized after 'praise'.

## Relevant technical choices:

* Replaced `sentence.indexOf( word );` by `sentence.search( new RegExp ( wordWithBoundaries, "ig" ) );`
* Added non-break spaces (`\u00a0` and ` `) to wordBoundary list.

## Test instructions

This PR can be tested by following these steps:

- Checkout release/1.20
- Use the browserified example. Don't forget to run a `grunt build:js`.
- Write `Who commented praise is due`.
- The sentence is incorrectly recognized as passive.

- Check out this branch.
- Don't forget to run a `grunt build:js`.
- Write `Who commented praise is due`.
- The sentence is not recognized as passive anymore.

Fixes #1214

### CODE REVIEW

File: js/stringProcessing/matchWordInSentence.js [hunk 1]
```diff
@@ -23,13 +24,22 @@ var isWordInSentence = function( word, sentence ) {
...
 	if ( occurrenceStart === -1 ) {
 		return false;
 	}
+	/*
+	If there is a word boundary before the matched word, the regex includes this word boundary in the match.
+	This means that occurrenceStart is the index of the word boundary before the match. Therefore 1 has to
+	be added to occurrenceStart, except when there is no word boundary before the match (i.e. at the start
+	of a sentence).
+	 */
+	if ( occurrenceStart > 0 ) {
```
Comment (Xyfi) [inline js/stringProcessing/matchWordInSentence.js]: Hier moet een betere oplossing voor te vinden zijn.

**Comment by Xyfi** [comment]
CR :+1:

I will create an issue to refactor `matchWordInSentence.js`, because the current solution is not very elegant, but since it works, is tested properly and needs to be released it passes.

**Comment by boblinthorst** [comment]
Acceptance: ok 👍, I'll go ahead and merge this one. @Xyfi , was the issue you wanted to make created? if so, perhaps reference this pull in it's description please.
