### PR TITLE
Fixes documentation for checkForTooLongSentences.js

### LINKED ISSUE #826: Improve documentation for checkForTooLongSentences.js
'sentences' is not an array containing sentence lengths, but an object containing both the sentence and its length.

### PR DESCRIPTION
**Pull request by IreneStr**
Fixes the incorrect documentation of 'sentences'.

Fixes #826

### CODE REVIEW

File: js/assessmentHelpers/checkForTooLongSentences.js [hunk 1]
```diff
@@ -3,7 +3,7 @@ var isSentenceTooLong = require( "../helpers/isValueTooLong" );
 
 /**
  * Checks for too long sentences.
- * @param {array} sentences The array containing sentence lengths.
+ * @param {object} sentences The object containing the text's sentences and their lengths.
```
Comment (terw-dan) [inline js/assessmentHelpers/checkForTooLongSentences.js]: This is an array with objects containing the sentences and their length.

**Comment by terw-dan** [comment]
Cr Done :+1:
