### PR TITLE
German passive voice tweaks

### LINKED ISSUE #955: Finetuning the German passive voice detection
We should tweak the German passive voice detection to make it even more accurate:
- [x] Delete 'gehört' from the auxiliary list because it causes too many false positives: the participle 'gehört' (from 'hören', 'to hear') is far more frequent than the auxiliary 'gehört' (from 'gehören', 'to belong').
- [x] Investigate whether participles ending in '-iert' cause too much false positives as well.
- [x] Investigate whether we need to check if participles with 'er-/ver-/ent-/be-/her-/zer-' are located immediately after the auxiliary. The futur aktiv indikativ uses the same participle as the passive voice, but in that case the auxiliary and participle are not adjacent: ich **wurde** das **behalten**/das **wurde** ich **behalten**.
- [x] Investigate if non-participles with 'er-/ver-/ent-/be-/her-/zer-', like 'beginnet' and 'beginnest', cause many false positives.
- [x] Add missing words to exceptionsParticiplesActive: gewerkschaft, entsteht

### PR DESCRIPTION
**Pull request by IreneStr**
## Summary

This PR can be summarized in the following changelog entry: N/A

## Relevant technical choices:

* Exclude words with 'er-/ver-/ent-/be-/her-/zer- ending with 'st' (but not -sst) from the participle regexes.
* Add über and ueber to the participle regexes. 
* Add non-participles starting with über/ueber and ending with -t to the participle exception list.
* Add irregular participles starting with über/ueber to the irregular list.
* Add 'gewerkschaft' and 'entsteht' to the participle exception list.
* Check whether a found participle is an auxiliary. 

## Test instructions

This PR can be tested by following these steps:

* Write a passive sentence with an participle starting with über. --> should be marked as passive
* Write an active sentence with a non-participle with über, ending with -t. --> should not be marked as passive
* Write an active sentence with an auxiliary ending in -t. --> should not be marked as passive
* Write an active sentence with an auxiliary and a verb ending in -st (but not -sst) --> should not be marked as passive

Fixes #955

### CODE REVIEW

File: js/researches/german/GermanParticiple.js [hunk 1]
```diff
@@ -73,4 +78,15 @@ GermanParticiple.prototype.hasHabenSeinException = function() {
...
 };
 
+/**
+ * Checks whether a found participle is an auxiliary.
+ * If a word is an auxiliary, it isn't a participle.
+ *
+ * @returns {boolean} Returns true if it is an auxiliary, otherwise returns false.
+ */
+GermanParticiple.prototype.isAuxiliary = function() {
+	return this.getParticiple().match( auxiliaryRegex ) !== null;
```
Comment (terw-dan) [inline js/researches/german/GermanParticiple.js]: Please don't use regexes for this, creating a function like `isInExceptionList` works a bit faster.

**Comment by terw-dan** [comment]
CR 1 done.

**Comment by terw-dan** [comment]
CR 2 done 👍

**Comment by terw-dan** [comment]
Acceptance 👍
