### PR TITLE
Fixes passive detection

### LINKED ISSUE #605: Passive voice doesn't handle text between quotation marks well
It looks like quotation marks interfere with passive voice detection. 

In the following sentence, the research should detect 'get lost' as a passive:
`As a result of that, a lot of blog posts will 'get lost' in a structure that is too flat.`
However, it doesn't.

### PR DESCRIPTION
**Pull request by terw-dan**
This pull fixes the passive detection. Only the last subsentence was pushed into an array with passives in stead of all of them, so a sentence was only passive if it was the last part. 

Includes another fix where the index is determined on a lowercased sentence.

For testing: See the added specs for an example of passive sentences. 

Fixes #605 (the issue wasn't the quotation marks).

### CODE REVIEW

File: js/researches/getPassiveVoice.js [hunk 1]
```diff
@@ -311,11 +312,11 @@ module.exports = function( paper ) {
 		var passive = false;
 		forEach( subSentences, function( subSentence ) {
 			passive = determinePassives( subSentence );
+			if ( passive === true ) {
+				passiveSentences.push( sentence );
+				passive = false;
```
Comment (IreneStr) [inline js/researches/getPassiveVoice.js]: This is probably unnecessary

**Comment by IreneStr** [comment]
CR done

**Comment by IreneStr** [comment]
CR 2 done 👍

**Comment by IreneStr** [comment]
Acceptance done 💯
